def show_alignment(refseq, aligned_seq, annotation_list):
    ann_start = annotation_list[0]

    ann_end = annotation_list[1]

    print(f"Annotated region: {ann_start} - {ann_end}")

    gap_eater = 0

    to_print = ""

    for i in range(max(len(refseq), len(aligned_seq))):

        if i % 10 == 0:
            to_print = str(i)

        if not to_print:

            print(" ", end=" ")

        else:

            print(to_print[0], end=" ")

            to_print = to_print[1:]

    print("")

    for i in range(max(len(refseq), len(aligned_seq))):
        unit = i % 10

        unit = " " if unit == 0 else unit

        print(unit, end="|" if i == ann_start - 1 or i == ann_end - 1 else " ")

    print("")

    for ref_l in refseq:
        print(ref_l, end=" ")

    print("")

    for alt_l in aligned_seq:
        print(alt_l, end=" ")

    print("")


x = "ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCCCGTCGGGCCCCCTCAAAGCCGAGATCGCGCAGAGACTTGAAGATGTCTTTGCAGGGAAGAACACCGATCTTGAGGCTCTCATGGAATGGCTAAAGACAAGACCAATCCTGTCACCTATGACTAAGGGGATTTTGGGATTTGTGTTCACGCTCACCGTGCCCAGTGAGCGAGGACTGCAGCGTAGACGCTTTGTCCAAAATGCTCTAAATGGAAATGGAGACCCAAACAACATGGACAGGGCAGTCAAACTGTACAAGAAATTGAAGAGAGAGATAACATTCCATGGGGCTAAAGAAGTTGCACTCAGTTACTCAACCGGTGCACTTGCCAGTTGTATGGGTCTCATATACAACAGGATGGGGACGGTGACCGCAGAAGTGGCATTGGGCCTAGTGTGTGCCACCTGTGAGCAGATTGCTGATTCACAGCATCGGTCTCACAGGCAGATAGCTACCACCACCAACCCACTAATCAGACATGAAAACAGAATGGTGTTGGCCAGTACTACAGCTAAGGCTATGGAGCAGATGGCTGGATCGAGTGAGCAAGCAGCAGAAGCCATGGAGGTTGCTAGTCAGGCTAGGCAAATGGTGCAAGCGATGAGGACCATTGGAACTCATCCTAGCTCCAGTGCCGGTCTGAGAGATGATCTCCTTGAAAATTTGCAGGCCTACCAAAAACGGATGGGAGTGCAACTGCAGCGATTCAAGTGATCCTCTCGTTATTGCCGCAAGTATCATTGGGATCTTGCACTTGATATTGTGGATTCTTGATCGCCTTTTCTTCAAATGCGTTTATCGTCGCCTTAAATACGGTTTGAAAAGAGGGCCTTCTACGGAAGGAGTACCTGAGTCCATGAGGGAAGAGTACCGGCAGGAACAGCAGAGTGCTGTGGATGTTGACGATGGTCATTTTGTCAACATAGAGCTGGAGTA"
show_alignment(x, x, [0, 981])
