version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - sqlite_data:/app/db  # Mount the shared volume where SQLite db file will be stored
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - sqlite_data:/app/db  # Frontend can access the same SQLite db if needed
    networks:
      - app-network

volumes:
  sqlite_data:
    driver: local  # A shared volume where the SQLite database file will be stored

networks:
  app-network:
    driver: bridge
