version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: fluhunterdb
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend  # Start only after the backend container starts
    networks:
      - app-network

  db:
    image: alpine:3.10
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fluhunterdb
    volumes:
      - db_data:/var/lib/sqlite/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
