[client]
showErrorDetails = true  # false
toolbarMode = "viewer"  # "auto"

[theme]
primaryColor = "black"
backgroundColor = "transparent"
secondaryBackgroundColor = "transparent"  # Background for sidebar and interactive widgets
textColor = "black"
# font = "sans serif/serif/monospace"