[client]
showErrorDetails = true  # false
toolbarMode = "viewer"  # "auto"

[theme]
primaryColor = "#FFF"  # Accent color for interactive elements
backgroundColor = "#09090B"
secondaryBackgroundColor = "#101B39"  # Background for sidebar and interactive widgets
textColor = "#FFF"
# font = "sans serif/serif/monospace"